// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxmizypbjbxarftxaply.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bWl6eXBiamJ4YXJmdHhhcGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzM0NjUsImV4cCI6MjA3MDI0OTQ2NX0.2ONH6IgaWfQ-1SEK3Ll3FfqpxOvjDEqc4ON0Uz94DVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});